name: Build package
on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: 0.8.4
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run Ruff lint check
        run: uv run ruff check --output-format=github .

      - name: Run Ruff format check
        run: uv run ruff format --check --diff

      - name: Run unit tests
        run: uv run pytest --cov --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
